#include"adc.h"


void ADC0_Init(void){
	SYSCTL_RCGCADC_R|=  ADC0_CLK_M;
	SYSCTL_RCGCGPIO_R|= GPIO_E_M;
	ADC0_ACTSS_R&=~(ADC0_ACTSS_SS3);
	ADC0_EMUX_R&=~(ADC0_SS3_TRIG);
	ADC0_SSMUX3_R = ADC0_SSMUX3;
	ADC0_SSCTL3_R |= (ADC0_SSCTL3_IEO|ADC0_SSCTL3_END0);
	ADC0_ACTSS_R|=ADC0_ACTSS_SS3;
GPIO_PORTE_AFSEL_R|= GPIO_PE2_M;
	GPIO_PORTE_DEN_R &=~(GPIO_PE2_M);
	GPIO_PORTE_AMSEL_R |= GPIO_PE2_M;
	GPIO_PORTE_DIR_R&=~(GPIO_PE2_M);
}

uint16_t ADC_SS3_In(){
	
	uint16_t data;
	ADC0_PSSI_R = ACD0_PSSI_SS3;
	while((ADC0_RIS_R & ADC0_RIS_INR3 )!=ADC0_RIS_INR3);
	data = ADC0_SSFIFO3_R & 0xFFF;
	
	ADC0_ISC_R = ADC0_RIS_INR3;
	return data;
}
